missing include - headerdemo.c
```bash
headerdemo.c: In function ‘main’:
headerdemo.c:536:44: warning: implicit declaration of function ‘atoi’ [-Wimplicit-function-declaration]
  536 |                                 interval = atoi(optarg);
      |                                            ^~~~
```